feat(CP4D Authentication): add ssl verification for self-signed certificates
IBM/python-sdk-core pull request #147
Opened 2022-07-27 12:25 UTC by LBExposito

These modifications allow the user to have a self-signed certificate in the SSL verification process when authenticating to an STT instance on CP4D.

The `verify` attribute is used by the [requests python module](https://pypi.org/project/requests/) to indicate the path to a custom CA Bundle ([resquests documentation](https://requests.readthedocs.io/en/latest/api/?highlight=verify)).

With these changes, it wont be necessary to disable ssl verification anymore when using a self-signed certificate with STT on CP4D.

2022-07-27 12:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/python-sdk-core?pullRequest=147) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/python-sdk-core?pullRequest=147) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/python-sdk-core?pullRequest=147) it.</sub>

2022-07-29 15:33 UTC, bobfang commented
to elaborate a bit more on this, these changes are for the Authentication step (getting a token). During regular SDK calls we can still pass `verify` as a kwarg and get it passed through to Requests.

2022-08-01 14:33 UTC, padamstx requested changes
Change look good, but we just need to add "verify" to the docstrings of each function that it was added to...

2022-08-01 14:33 UTC, padamstx commented on ibm_cloud_sdk_core/authenticators/cp4d_authenticator.py
> +                 verify: Optional[str] = None) -> None:
Please also document the `verify` parameter in the docstrings above, similar to headers, proxies, etc.

2022-08-01 14:33 UTC, padamstx commented on ibm_cloud_sdk_core/token_managers/cp4d_token_manager.py
> +                 verify: Optional[str] = None) -> None:
Please document `verify` in the docstrings above.

2022-08-01 15:53 UTC, LBExposito commented
Docstrings are updated !

2022-08-01 20:19 UTC, padamstx approved these changes
LGTM

2022-08-01 20:20 UTC, merged

2022-08-01 20:26 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 3.16.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/python-sdk-core/releases/tag/v3.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: